<script setup lang="ts">
import { colorsHex } from '@/utils/theme'
</script>
<template>
  <div class="fixed top-0 left-0 z-10 w-full h-full flex justify-center items-center">
    <div class="flex flex-col items-center">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="150"
        height="150"
        viewBox="0 0 24 24"
      >
        <rect
          width="9"
          height="9"
          x="1.5"
          y="1.5"
          :fill="colorsHex[0].primary"
          rx="1"
        >
          <animate
            id="svgSpinnersBlocksScale0"
            attributeName="x"
            begin="0;svgSpinnersBlocksScale1.end+0.15s"
            dur="0.6s"
            keyTimes="0;.2;1"
            values="1.5;.5;1.5"
          />
          <animate
            attributeName="y"
            begin="0;svgSpinnersBlocksScale1.end+0.15s"
            dur="0.6s"
            keyTimes="0;.2;1"
            values="1.5;.5;1.5"
          />
          <animate
            attributeName="width"
            begin="0;svgSpinnersBlocksScale1.end+0.15s"
            dur="0.6s"
            keyTimes="0;.2;1"
            values="9;11;9"
          />
          <animate
            attributeName="height"
            begin="0;svgSpinnersBlocksScale1.end+0.15s"
            dur="0.6s"
            keyTimes="0;.2;1"
            values="9;11;9"
          />
        </rect>
        <rect
          width="9"
          height="9"
          x="13.5"
          y="1.5"
          :fill="colorsHex[1].primary"
          rx="1"
        >
          <animate
            attributeName="x"
            begin="svgSpinnersBlocksScale0.begin+0.15s"
            dur="0.6s"
            keyTimes="0;.2;1"
            values="13.5;12.5;13.5"
          />
          <animate
            attributeName="y"
            begin="svgSpinnersBlocksScale0.begin+0.15s"
            dur="0.6s"
            keyTimes="0;.2;1"
            values="1.5;.5;1.5"
          />
          <animate
            attributeName="width"
            begin="svgSpinnersBlocksScale0.begin+0.15s"
            dur="0.6s"
            keyTimes="0;.2;1"
            values="9;11;9"
          />
          <animate
            attributeName="height"
            begin="svgSpinnersBlocksScale0.begin+0.15s"
            dur="0.6s"
            keyTimes="0;.2;1"
            values="9;11;9"
          />
        </rect>
        <rect
          width="9"
          height="9"
          x="13.5"
          y="13.5"
          :fill="colorsHex[2].primary"
          rx="1"
        >
          <animate
            attributeName="x"
            begin="svgSpinnersBlocksScale0.begin+0.3s"
            dur="0.6s"
            keyTimes="0;.2;1"
            values="13.5;12.5;13.5"
          />
          <animate
            attributeName="y"
            begin="svgSpinnersBlocksScale0.begin+0.3s"
            dur="0.6s"
            keyTimes="0;.2;1"
            values="13.5;12.5;13.5"
          />
          <animate
            attributeName="width"
            begin="svgSpinnersBlocksScale0.begin+0.3s"
            dur="0.6s"
            keyTimes="0;.2;1"
            values="9;11;9"
          />
          <animate
            attributeName="height"
            begin="svgSpinnersBlocksScale0.begin+0.3s"
            dur="0.6s"
            keyTimes="0;.2;1"
            values="9;11;9"
          />
        </rect>
        <rect
          width="9"
          height="9"
          x="1.5"
          y="13.5"
          :fill="colorsHex[3].primary"
          rx="1"
        >
          <animate
            id="svgSpinnersBlocksScale1"
            attributeName="x"
            begin="svgSpinnersBlocksScale0.begin+0.45s"
            dur="0.6s"
            keyTimes="0;.2;1"
            values="1.5;.5;1.5"
          />
          <animate
            attributeName="y"
            begin="svgSpinnersBlocksScale0.begin+0.45s"
            dur="0.6s"
            keyTimes="0;.2;1"
            values="13.5;12.5;13.5"
          />
          <animate
            attributeName="width"
            begin="svgSpinnersBlocksScale0.begin+0.45s"
            dur="0.6s"
            keyTimes="0;.2;1"
            values="9;11;9"
          />
          <animate
            attributeName="height"
            begin="svgSpinnersBlocksScale0.begin+0.45s"
            dur="0.6s"
            keyTimes="0;.2;1"
            values="9;11;9"
          />
        </rect>
      </svg>
      <div class="mt-4 font-bold text-white">Your answer is being processed</div>
    </div>
  </div>
</template>
