version: '3.8'

services:
  quizzfly-client:
    image: quizzfly-client
    container_name: quizzfly-client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    restart: always
