export const avatars = [
  'https://avataaars.io/?avatarStyle=Circle&topType=ShortHairShortRound&accessoriesType=Kurt&hairColor=Blonde&facialHairType=MoustacheMagnum&facialHairColor=BrownDark&clotheType=CollarSweater&clotheColor=PastelOrange&eyeType=Default&eyebrowType=SadConcernedNatural&mouthType=Tongue&skinColor=DarkBrown',
  'https://avataaars.io/?avatarStyle=Circle&topType=LongHairStraight&accessoriesType=Prescription01&hairColor=Red&facialHairType=MoustacheMagnum&facialHairColor=Red&clotheType=BlazerShirt&clotheColor=PastelYellow&eyeType=EyeRoll&eyebrowType=UnibrowNatural&mouthType=Smile&skinColor=Pale',
  'https://avataaars.io/?avatarStyle=Circle&topType=ShortHairSides&accessoriesType=Wayfarers&hairColor=BlondeGolden&facialHairType=MoustacheMagnum&facialHairColor=Platinum&clotheType=BlazerShirt&eyeType=Hearts&eyebrowType=FlatNatural&mouthType=Tongue&skinColor=Light',
  'https://avataaars.io/?avatarStyle=Circle&topType=ShortHairTheCaesarSidePart&accessoriesType=Prescription01&hairColor=Black&facialHairType=MoustacheMagnum&facialHairColor=BlondeGolden&clotheType=GraphicShirt&clotheColor=Pink&graphicType=Deer&eyeType=Wink&eyebrowType=UpDownNatural&mouthType=Sad&skinColor=DarkBrown',
  'https://avataaars.io/?avatarStyle=Circle&topType=ShortHairSides&accessoriesType=Kurt&hairColor=Black&facialHairType=Blank&facialHairColor=Blonde&clotheType=ShirtVNeck&clotheColor=PastelBlue&graphicType=Resist&eyeType=Dizzy&eyebrowType=Default&mouthType=Default&skinColor=Black',
  'https://avataaars.io/?avatarStyle=Circle&topType=ShortHairDreads02&accessoriesType=Prescription01&hairColor=BlondeGolden&facialHairType=MoustacheMagnum&facialHairColor=Platinum&clotheType=CollarSweater&clotheColor=PastelOrange&eyeType=Squint&eyebrowType=UnibrowNatural&mouthType=ScreamOpen&skinColor=Tanned',
  'https://avataaars.io/?avatarStyle=Circle&topType=ShortHairShaggyMullet&accessoriesType=Kurt&hairColor=Auburn&facialHairType=MoustacheMagnum&facialHairColor=Brown&clotheType=BlazerSweater&clotheColor=Pink&eyeType=Squint&eyebrowType=SadConcernedNatural&mouthType=Eating&skinColor=Pale',
  'https://avataaars.io/?avatarStyle=Circle&topType=LongHairNotTooLong&accessoriesType=Prescription01&hairColor=Brown&facialHairType=Blank&facialHairColor=BlondeGolden&clotheType=ShirtCrewNeck&clotheColor=Blue01&eyeType=Dizzy&eyebrowType=SadConcerned&mouthType=Twinkle&skinColor=DarkBrown',
  'https://avataaars.io/?avatarStyle=Circle&topType=LongHairCurly&accessoriesType=Round&hairColor=BlondeGolden&facialHairType=BeardMajestic&facialHairColor=Black&clotheType=ShirtCrewNeck&clotheColor=PastelOrange&eyeType=EyeRoll&eyebrowType=Angry&mouthType=Vomit&skinColor=Brown',
  'https://avataaars.io/?avatarStyle=Circle&topType=LongHairCurvy&accessoriesType=Prescription01&hairColor=Blue&facialHairType=BeardMedium&facialHairColor=Red&clotheType=ShirtCrewNeck&clotheColor=Gray01&eyeType=Dizzy&eyebrowType=DefaultNatural&mouthType=Serious&skinColor=Yellow',
  'https://avataaars.io/?avatarStyle=Circle&topType=WinterHat4&accessoriesType=Blank&hatColor=PastelBlue&hairColor=BrownDark&facialHairType=BeardMedium&facialHairColor=Platinum&clotheType=BlazerShirt&clotheColor=White&eyeType=EyeRoll&eyebrowType=SadConcernedNatural&mouthType=Tongue&skinColor=Yellow',
]
