export const musics = [
  { value: 'City-shadows', label: 'City-shadows' },
  { value: 'Cool-action', label: 'Cool-action' },
  { value: 'Cool-energetic', label: 'Cool-energetic' },
  { value: 'Cool-strong', label: 'Cool-strong' },
  { value: 'Cool-stylish', label: 'Cool-stylish' },
  { value: 'Final-day', label: 'Final-day' },
  { value: 'Funny-bgm', label: 'Funny-bgm' },
  { value: 'Funny-kids', label: 'Funny-kids' },
  { value: 'Funny-story', label: 'Funny-story' },
  { value: 'Hard-rock', label: 'Hard-rock' },
  { value: 'Harmonica', label: 'Harmonica' },
  { value: 'Hitting-hard', label: 'Hitting-hard' },
  { value: 'Intense-brostep', label: 'Intense-brostep' },
  { value: 'Jazz-happy', label: 'Jazz-happy' },
  { value: 'Life-wandering', label: 'Life-wandering' },
  { value: 'Playful-fun', label: 'Playful-fun' },
  { value: 'Prank', label: 'Prank' },
  { value: 'Pun', label: 'Pun' },
  { value: 'Puppy-love', label: 'Puppy-love' },
  { value: 'Quirky-fun', label: 'Quirky-fun' },
  { value: 'Quirky-playful', label: 'Quirky-playful' },
  { value: 'Silly-intro', label: 'Silly-intro' },
  {
    value: 'Suspense-cartoon',
    label: 'Suspense-cartoon',
  },
  { value: 'Texas-blues', label: 'Texas-blues' },
  {
    value: 'Upbeat-background',
    label: 'Upbeat-background',
  },
  { value: 'Upbeat-mission', label: 'Upbeat-mission' },
]
